/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ChainLinks;
import io.swagger.client.model.ExtIds;
import io.swagger.client.model.StatusParams;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Chain
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-30T15:28:24.262574+02:00[Europe/Madrid]")
public class Chain {
  @SerializedName("chainId")
  private String chainId = null;

  @SerializedName("extIds")
  private ExtIds extIds = null;

  @SerializedName("status")
  private StatusParams status = null;

  @SerializedName("synced")
  private Boolean synced = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("links")
  private ChainLinks links = null;

  public Chain chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public Chain extIds(ExtIds extIds) {
    this.extIds = extIds;
    return this;
  }

   /**
   * Get extIds
   * @return extIds
  **/
  @Schema(description = "")
  public ExtIds getExtIds() {
    return extIds;
  }

  public void setExtIds(ExtIds extIds) {
    this.extIds = extIds;
  }

  public Chain status(StatusParams status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public StatusParams getStatus() {
    return status;
  }

  public void setStatus(StatusParams status) {
    this.status = status;
  }

  public Chain synced(Boolean synced) {
    this.synced = synced;
    return this;
  }

   /**
   * Chain sync status:   * &#x60;true&#x60; - All entries loaded   * &#x60;false&#x60; - Chain is syncing with blockchain 
   * @return synced
  **/
  @Schema(description = "Chain sync status:   * `true` - All entries loaded   * `false` - Chain is syncing with blockchain ")
  public Boolean isSynced() {
    return synced;
  }

  public void setSynced(Boolean synced) {
    this.synced = synced;
  }

  public Chain createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Chain links(ChainLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public ChainLinks getLinks() {
    return links;
  }

  public void setLinks(ChainLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chain chain = (Chain) o;
    return Objects.equals(this.chainId, chain.chainId) &&
        Objects.equals(this.extIds, chain.extIds) &&
        Objects.equals(this.status, chain.status) &&
        Objects.equals(this.synced, chain.synced) &&
        Objects.equals(this.createdAt, chain.createdAt) &&
        Objects.equals(this.links, chain.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chainId, extIds, status, synced, createdAt, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chain {\n");
    
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    extIds: ").append(toIndentedString(extIds)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    synced: ").append(toIndentedString(synced)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
