/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ExtIds;
import io.swagger.client.model.StatusParams;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Entry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-30T15:28:24.262574+02:00[Europe/Madrid]")
public class Entry {
  @SerializedName("entryHash")
  private String entryHash = null;

  @SerializedName("chainId")
  private String chainId = null;

  @SerializedName("extIds")
  private ExtIds extIds = null;

  @SerializedName("content")
  private byte[] content = null;

  @SerializedName("status")
  private StatusParams status = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  public Entry entryHash(String entryHash) {
    this.entryHash = entryHash;
    return this;
  }

   /**
   * Get entryHash
   * @return entryHash
  **/
  @Schema(description = "")
  public String getEntryHash() {
    return entryHash;
  }

  public void setEntryHash(String entryHash) {
    this.entryHash = entryHash;
  }

  public Entry chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public Entry extIds(ExtIds extIds) {
    this.extIds = extIds;
    return this;
  }

   /**
   * Get extIds
   * @return extIds
  **/
  @Schema(description = "")
  public ExtIds getExtIds() {
    return extIds;
  }

  public void setExtIds(ExtIds extIds) {
    this.extIds = extIds;
  }

  public Entry content(byte[] content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public byte[] getContent() {
    return content;
  }

  public void setContent(byte[] content) {
    this.content = content;
  }

  public Entry status(StatusParams status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public StatusParams getStatus() {
    return status;
  }

  public void setStatus(StatusParams status) {
    this.status = status;
  }

  public Entry createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entry entry = (Entry) o;
    return Objects.equals(this.entryHash, entry.entryHash) &&
        Objects.equals(this.chainId, entry.chainId) &&
        Objects.equals(this.extIds, entry.extIds) &&
        Objects.equals(this.content, entry.content) &&
        Objects.equals(this.status, entry.status) &&
        Objects.equals(this.createdAt, entry.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryHash, chainId, extIds, content, status, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entry {\n");
    
    sb.append("    entryHash: ").append(toIndentedString(entryHash)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    extIds: ").append(toIndentedString(extIds)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
