/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse200Result
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-30T15:28:24.262574+02:00[Europe/Madrid]")
public class InlineResponse200Result {
  @SerializedName("version")
  private String version = null;

  @SerializedName("blockchainHeight")
  private Integer blockchainHeight = null;

  @SerializedName("apiHeight")
  private Integer apiHeight = null;

  public InlineResponse200Result version(String version) {
    this.version = version;
    return this;
  }

   /**
   * API version
   * @return version
  **/
  @Schema(example = "1.4.2", description = "API version")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public InlineResponse200Result blockchainHeight(Integer blockchainHeight) {
    this.blockchainHeight = blockchainHeight;
    return this;
  }

   /**
   * Latest block on the blockchain
   * @return blockchainHeight
  **/
  @Schema(example = "215838", description = "Latest block on the blockchain")
  public Integer getBlockchainHeight() {
    return blockchainHeight;
  }

  public void setBlockchainHeight(Integer blockchainHeight) {
    this.blockchainHeight = blockchainHeight;
  }

  public InlineResponse200Result apiHeight(Integer apiHeight) {
    this.apiHeight = apiHeight;
    return this;
  }

   /**
   * Latest block on API server (follows the blockchain)
   * @return apiHeight
  **/
  @Schema(example = "215838", description = "Latest block on API server (follows the blockchain)")
  public Integer getApiHeight() {
    return apiHeight;
  }

  public void setApiHeight(Integer apiHeight) {
    this.apiHeight = apiHeight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Result inlineResponse200Result = (InlineResponse200Result) o;
    return Objects.equals(this.version, inlineResponse200Result.version) &&
        Objects.equals(this.blockchainHeight, inlineResponse200Result.blockchainHeight) &&
        Objects.equals(this.apiHeight, inlineResponse200Result.apiHeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, blockchainHeight, apiHeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Result {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    blockchainHeight: ").append(toIndentedString(blockchainHeight)).append("\n");
    sb.append("    apiHeight: ").append(toIndentedString(apiHeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
