/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse400
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-30T15:28:24.262574+02:00[Europe/Madrid]")
public class InlineResponse400 {
  @SerializedName("result")
  private Boolean result = null;

  @SerializedName("code")
  private Integer code = null;

  @SerializedName("error")
  private String error = null;

  public InlineResponse400 result(Boolean result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(example = "false", description = "")
  public Boolean isResult() {
    return result;
  }

  public void setResult(Boolean result) {
    this.result = result;
  }

  public InlineResponse400 code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Error codes:   * &#x60;1410&#x60; - Binding data error   * &#x60;1420&#x60; - Validation error   * &#x60;1430&#x60; - Pagination error 
   * @return code
  **/
  @Schema(example = "1420", description = "Error codes:   * `1410` - Binding data error   * `1420` - Validation error   * `1430` - Pagination error ")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public InlineResponse400 error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Error description
   * @return error
  **/
  @Schema(example = "...", description = "Error description")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse400 inlineResponse400 = (InlineResponse400) o;
    return Objects.equals(this.result, inlineResponse400.result) &&
        Objects.equals(this.code, inlineResponse400.code) &&
        Objects.equals(this.error, inlineResponse400.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, code, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse400 {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
