/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets sortParams
 */
@JsonAdapter(SortParams.Adapter.class)
public enum SortParams {
  ASC("asc"),
  DESC("desc");

  private String value;

  SortParams(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SortParams fromValue(String text) {
    for (SortParams b : SortParams.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SortParams> {
    @Override
    public void write(final JsonWriter jsonWriter, final SortParams enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SortParams read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return SortParams.fromValue(String.valueOf(value));
    }
  }
}
