/*
 * Factom PRO API
 * Factom PRO is a cloud blockchain gateway for securing your business data. Store data on the Bitcoin and Ethereum blockchains at a low fixed price of $0.01 per write. No cryptocurrency. No nodes.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: support@factom.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExtIds;
import io.swagger.client.model.InlineResponse2006;
import io.swagger.client.model.InlineResponse400;
import io.swagger.client.model.InlineResponse401;
import io.swagger.client.model.InlineResponse500;
import io.swagger.client.model.NewEntry;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntriesApi
 */
@Ignore
public class EntriesApiTest {

    private final EntriesApi api = new EntriesApi();

    /**
     * Create entry
     *
     * This endpoint allows you to create entry into Factom chain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEntryTest() throws ApiException {
        NewEntry body = null;
        String callbackUrl = null;
        InlineResponse2006 response = api.createEntry(body, callbackUrl);

        // TODO: test validations
    }
    /**
     * Get entry
     *
     * This endpoint returns Factom entry by it&#x27;s hash.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntryTest() throws ApiException {
        String entryHash = null;
        InlineResponse2006 response = api.getEntry(entryHash);

        // TODO: test validations
    }
}
